version: '3.5'

services:
  desktop:
    build: .
    #image: cyb10101/desktop:latest

    volumes:
      - ~/projects/docker_desktop/storage/downloads:/home/application/Downloads
      - ~/projects/docker_desktop/storage/.mozilla:/home/application/.mozilla

    environment:
      - DISPLAY_WIDTH=1366
      - DISPLAY_HEIGHT=768
      - PASSWORD=Admin123!
      - NX_PORT=4000
    ports:
      - 4000:4000
      - 4467:4467/udp
    cap_add:
      - SYS_PTRACE
    working_dir: /home/application
