version: '3.8'

services:
  app:
    image: desktop
    build: .
    hostname: desktop
    volumes:
      #- ~/Downloads/public:/home/application/Desktop/public
      - ./storage/downloads:/home/application/Downloads
      - ./storage/.mozilla:/home/application/.mozilla
    environment:
      - DISPLAY_WIDTH=1366
      - DISPLAY_HEIGHT=768
      - PASSWORD=Admin123!
      - NX_PORT=4001
    expose:
      - 4001
    ports:
      - 4001:4001
      - 4467:4467/udp
    cap_add:
      - SYS_PTRACE
    working_dir: /home/application
