#!/usr/bin/env bash

BUILD_ARCH=$(echo "${DOCKERFILE_PATH}" | cut -d '.' -f 2)

if [ "${BUILD_ARCH}" == "Dockerfile" ]; then
  echo 'qemu-user-static: Registration not required for current arch';
  exit 0;
fi

docker run --rm --privileged multiarch/qemu-user-static:register --reset
